### ISSUE TITLE
Models for ARFF types

### ISSUE THREAD

**Issue by tahaceritli** [alan-turing-institute/ptype#161]
Hi @rolyp ,

I noticed that ptype gives an error when installed via pip:

from ptype.Ptype import Ptype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tceritli/anaconda3/lib/python3.7/site-packages/ptype/Ptype.py", line 3, in <module>
    from ptype.Column import (
  File "/Users/tceritli/anaconda3/lib/python3.7/site-packages/ptype/Column.py", line 146, in <module>
    _column2ARFF = _Column2ARFF(project_root() + "/../models/")
  File "/Users/tceritli/anaconda3/lib/python3.7/site-packages/ptype/Column.py", line 128, in __init__
    self.normalizer = joblib.load(model_folder + "robust_scaler.pkl")
  File "/Users/tceritli/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 590, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tceritli/anaconda3/lib/python3.7/site-packages/ptype/../models/robust_scaler.pkl'

It seems that the models used for ARFF type inference are not downloaded during the installation. We could solve this issue by adding the files I suppose. But, perhaps we should just remove ARFF type inference. What do you think?

**Comment by rolyp** [comment]
Ah. Yes, perhaps we need to bundle those somehow into the wheel. But I
agree that removing ARFF type inference makes a lot more sense – it’s not
documented, or used for anything in any of the example notebooks. I guess
we could do that and remove `robust_scaler.pkl` and any other models at the
same time. If you’re happy doing that I suggest going ahead, let me know if
you need me to do anything.

**Comment by tahaceritli** [comment]
Thanks! I have removed ARFF related stuff including the inference and the corresponding tests (see https://github.com/alan-turing-institute/ptype/pull/163). 

I merged it to develop. Should I merge this to release as well? I suppose I would also need to modify the changelog.

**Comment by rolyp** [comment]
Cool. Yes, to merge to release, there are a couple of useful things to know:

-- git pull on ‘release’ and merge into ‘develop’ first, so you’re up to
date
-- update CHANGELOG.rst, using one version number *above* the current one
in __version__.py
-- create the pull request to merge to ‘release’; you’ll need to swap the
roles of ‘release’ and ‘develop’ (since GitHub will try to merge into
‘develop’ by default)

(Nothing goes wrong if we don’t update the changelog, but I guess it’s a
good habit to get into :)

Roly

**Comment by tahaceritli** [comment]
Great! Thanks for the tips! 

But I still managed to mess up slightly :/ I thought that I would need to update the version numbers in ptype/.bumpversion.cfg and ptype/__version__ as well. As a result (I believe), the ptype version in PyPI is changed to 0.2.12 rather than 0.2.11 (see https://pypi.org/project/ptype/#history). So, the versions reported in github and PyPI are different.

**Comment by tahaceritli** [comment]
ARFF types are brought back with ptype-cat integration (see https://github.com/alan-turing-institute/ptype/pull/169)
