### ISSUE TITLE
Downcast column to inferred Pandas data type

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype#37]
- [x] for the “normal” (typed) projection, each column should have the corresponding inferred type
- [x] `transform_schema`

**Comment by rolyp** [comment]
Notes from @GjjvdBurg:

> This occurred to me just near the end of the meeting, but what if we
> output a very simple "schema" with the detected types? The user can then
> edit this schema where necessary and feed it back to ptype to cast the
> columns to according to the schema.
> 
> For example, say we have a categorical column with incorrectly detected
> 'ERR' class, which the user corrects:
> 
> ```
> >>> schema = ptype.fit_schema(df)
> >>> schema
> {
>    'col_1': ('Int64',),
>    'col_2': ('Categorical', 'A', 'B', 'ERR'),
>    'col_3': ('String',),
>    'col_4': ('Float',),
> }
> 
>  >>> schema['col_2'] = ('Categorical', 'A', 'B')
>  >>> typed_df = ptype.transform_schema(df, schema)
> ```
> This could easily be automated if the user prefers not to inspect and
> interact with ptype. An advantage of this approach is that the “schema”
> object is a simple python dictionary, which is easy to manipulate. You
> could then also add a method to return the schema with the second-best
> guess for a particular column, etc.
> 
> As an aside, a potentially good list of high-level data types for python
> can be found in the Pydantic library:
> https://pydantic-docs.helpmanual.io/usage/types/
>

**Comment by rolyp** [comment]
And reply from @tahaceritli:

> Thanks! This sounds like a sensible approach, although I do not know how frequently people use schemas in practice.
> 
> IMO, it would be fairly easy to implement your proposal to handle misclassified categorical values. However, we would still need to think about how to feed this information back to the model. I guess that one simple solution would be to fix the row type distribution of misclassified categorical values (e.g., ‘ERR’ in your example) after user feedback so that they are promoted as anomalies and discarded during type inference of that column. On the other hand, we may want to have a solution where we update some of the PFSMs.
> 
> BTW, I have spotted some python packages to manage schemas (note that the last one belongs to the Pandas library):
> - https://pypi.org/project/pandas-schema/,
> - https://pandera.readthedocs.io/en/stable/dataframe_schemas.html
> - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.build_table_schema.html.
> 
> These packages introduce validation functions to detect inconsistencies, where one function checks whether the data values of a column are in the allowed list or not. Perhaps we could also provide these types of functions.

**Comment by GjjvdBurg** [comment]
See also #62 and #64 :)
