### ISSUE TITLE
Non-deterministic training tests

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype#60]
Training relies on `scipy.optimize.line_search`, which appears to be a stochastic optimisation method. At least, we get different results each time we run the algorithm: while `training_error.json` is constant, `training_runner_initial.json` and `training_runner_final.json` are different on each run. We should be able to determinise by doing something like `numpy.random.seed(0)`, but our initial experiment with this didn’t work.

For now `training_runner_initial.json` and `training_runner_final.json` are added to `models/.gitignore` and are not compared during the training tests.

- [x] remove `.json` files from `.gitignore` and add to version control
- [x] restrict interest to `training_runner_initial.json` initially
- [x] verify that `alphabet` differs only in ordering of elements
- [x] `set` constructor may not be deterministic ([wtf?](https://stackoverflow.com/questions/51927850/is-set-deterministic)) – doesn’t seem to matter but remove from `create_pfsm_from_fsm` anyway
- [x] try sorting the FSM `alphabet` when converting to PFSM
- [x] check sorting FSM alphabet determinises training_runner_final.json as well
- [x] verify we still need `numpy.random.seed`
- [x] fail `training_test` if models compare unequal after test run
  - [x] `Ptype.train_model` to return `PFSMRunner` and `training_error` rather than writing to file
  - [x] write to file in `test_ptype.py` instead
- [x] reenabling notebook tests interfaces with training tests:
  - [x] `Machine.word_prob` mutated by `calculate_probability` should be local
  - `Machine.candidate_path_prob`, `ignore`, `repeat_count` should also be local?
    - [x] delete duplicate impl of `find_possible_targets`
    - [x] delete `find_possible_targets_counts`
    - [x] merge `find_possible_targets_counts_final` with `find_possible_targets`
    - [x] factor duplicate impls of `calculate_probability` through superclass
    - [x] delete `calculate_probability_new`?
    - [x] delete `calculate_gradient_final_state` (unused)
    - [x] delete `Model.g_col`, `Machine.calculate_gradient_abc_new_optimized`
    - [x] delete `reg_exp`, `I_backup` and `F_backup` fields
    - [x] delete `add_state`, `add_transition`, `count_number_params`, `num_states`, `count_c_final`
    - [x] `candidate_path_prob` as an accumulator parameter
    - [x] `ignore` as a parameter</s>
    - [x] `repeat_count`, `repeat_state` fields (unused)
  - `py/b64` discrepancy in 2 places in each file 🤦 
    - [x] with `unpicklable=False`: I get `-9.210340371976182` vs `9.210340371976184`
    - [x] for now move `notebook_tests` to the end so it doesn’t interfere
  - [x] hack in `git diff` to see if that reveals anything significant
  - [x] verify local behaviour is consistent with server when running full `virtualenv` script

**Comment by tahaceritli** [comment]
I'm surprised that training_runner_initial.json changes. It doesn't go through the line search. Can there be another reason for this?

**Comment by rolyp** [comment]
Weird, I also just got a change in `training_error.json`: https://github.com/alan-turing-institute/ptype-dmkd/commit/a702b57f269f375beaa0f6cb16081d2211fbcda0
