### ISSUE TITLE
Initial pass over magic numbers used as indices

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype#68]
There are various places in the code where [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) are explicitly used (or implicitly assumed) as indices (struck through means no longer relevant):
- <s>`reclassify_column` (`5`)</s>
- [x] `get_arff` (`7`, `8`)
- [x] `sorted_posterior` (`0`, `1`, `2`, `3`, `4`)
- [x] `0`, `1`, `2` in `p_z[:, j, 0] = np.exp(x1 - log_mx - np.log(sm))` (etc) in `Model.py` should be 
- <s>`self.p_z[i, :] = [1.0, 0.0, 0.0]` in `Column.py` – sequence looks suspicious</s>
- [x] `7` in `len(self.alphabet) - 7` in `Machine.Missing.probability`
- <s>`0`, `1` in `plot_row_type_posterior`</s>
- [x] lots of occurrences of `2` inside `Machines`
- [x] magic numbers in Ptype setters and getters for na_values and anomalous_values
- `logP` schenanigans (`LLHOOD_TYPE_START_INDEX`, `MISSING_INDEX - 1`, etc)

Deferred for now:
- `0`, `1`, `2` throughout `g_col_marginals`
- indexing of `PI`
- `-2`, `-1` in `Trainer.train`

**Comment by rolyp** [comment]
@tahaceritli Couple of questions for you:
- In the enum `Feature`, does anything hinge on the choice of values for `U` and `U_CLEAN`? (For example could I replace these by 1 and 0 and would everything still work?)
- What are `U_RATIO` and `U_RATIO_CLEAN` used for?

**Comment by tahaceritli** [comment]
@rolyp see my response below:

- U_RATIO and U_RATIO_CLEAN are used as features for canonical type inference (see the get_arff function of the Column2ARFF class where we normalize some of the features). Note that their corresponding indices are not used at the moment. However, we would need them if we want to use these features (e.g., for visualization and printing). 

- That could work, but we need to update the following line:
features[[Feature.U.value, Feature.U_CLEAN.value]] = self.normalizer.transform(
            features[[Feature.U.value, Feature.U_CLEAN.value]].reshape(1, -1)
        )[0]

Note that features is equal to np.array(list(posterior) + [u_ratio, u_ratio_clean, U, U_clean]). What we could do is to replace u_ratio, u_ratio_clean, U, U_clean respectively with -4, -3, -2 and -1. This way it would work regardless of the data types given in ptype.types. At the moment, it assumes that there are 5 data types are given and that these new features begin at the index 5.

Let me know if there is something not clear.

**Comment by rolyp** [comment]
First pass over this done, much more to do but best deal with as part of separate cleanup/reengineering tasks.
