### ISSUE TITLE
Schema transform

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/ptype#79]
See [notebook](https://github.com/alan-turing-institute/ptype-dmkd/blob/develop/notebooks/correct-column-type.ipynb). To do:
- [x] set the scene better for the error when calling `lm.fit`
- [x] have Ptype report on how it automates this step (i.e. summarise anomalous/erroneous rows)
- [x] rewrite bullet points at beginning into proper text
- [x] interweave explanatory text into Part 2

Done/dropped:
- Part 2 seems to improve on Part 1 only in saving the user from converting ‘?’ to `pd.na`
- <s>maybe duplication between Part 2 and Part 1 isn’t necessary – maybe present Ptype usage _within_ a larger scenario?</s>
- [x] better name for use case
- [x] rename `transform_schema`
- <s>`show_schema` should be a method on schema object</s> – see #118 
- <s>`Ptype` should describe inferred type as `Int64`, not `integer`</s> – see #117 
- [x] remove unnecessary imports
- [x] move summary above to beginning of notebook?
- [x] move Ptype imports to where they’re first used
- [x] rather than showing `df.loc[130]`, point out that it’s not obvious where the problem is in the dataset
- [x] run query to show occurrences of ‘?’
- [x] remove metrics such as `mean_absolute_error` 
- [x] instead of `build_table_schema`, why not just show `dtypes` again?
- [x] dtypes are not automatically changed after replacing ‘?’ in part 1. add another step to change it
- [x] explain `dtype=’str’` step
- [x] inline `scatter_plot` helper

**Comment by tahaceritli** [comment]
fixed some of the items above in https://github.com/alan-turing-institute/ptype-dmkd/pull/99/

**Comment by rolyp** [comment]
Summary:

Part 1 (solve data cleaning problem without Ptype):

- import dataset using Pandas `read_csv`
- run linear regression on data
- error occurs because of missing data: could not convert string to float: ‘?’
- inspect `dtypes` property of dataframe to see the problem
- use Pandas to change encoding of missing data, remove relevant rows
- run linear regression again (no errors), plot results
- use `dtypes` to verify that we now have appropriate column types

Part 2 (how Ptype makes this problem easier):
- import dataset using Pandas `read_csv`, but this time with `dtype=’str’`
- instantiate Ptype
- ask Ptype to infer schema; show inferred types
- ask Ptype to adjust type of dataframe to match schema
- inspect transformed dataframe to verify types as expected
- then as per Part 1 to remove missing data and continue
